Ensure reactive context is propagated
micronaut-projects/micronaut-graphql pull request #512
Opened 2024-03-05 18:35 UTC by jeremyg484

DefaultGraphQLInvocation and DefaultGraphQLExecutionInputCustomizer are updated
to use Mono and Flux in their internal implementation in order to ensure that
the Micronaut PropagationContext is carried appropriately through the invocation
flow. Previous use of the bare io.micronaut.core.async.publisher.Publishers API
in DefaultGraphQLExecutionInputCustomizer was causing the context not to be
propagated as desired when including the Micrometer Context Propagation library.

A test is added to verify the context propagation works as expected.

Some additional cleanup is done throughout the test suite to reduce the scope
of included Micronaut beans to the specific tests in order to make it easier to
test different setups.

Resolves #495

2024-03-06 06:48 UTC, sdelamo requested changes
Looking good. 

Can we rewrite the snippets:

```java
    ApplicationContext context = new DefaultApplicationContext(Environment.TEST)
        context.environment.addPropertySource(PropertySource.of(
                ["spec.name": GraphQLConfigurationSpec.simpleName,
                 "graphql.graphiql.enabled": false]
        ))
        context.start()
```

with: 

```java
ApplicationContext context = ApplicationContext.run(["spec.name": GraphQLConfigurationSpec.simpleName,  "graphql.graphiql.enabled": false])
```

I don't think we should be using `DefaultApplicationContext` class directly which is an internal class.

2024-03-06 11:31 UTC, timyates approved these changes

2024-03-06 16:14 UTC, jeremyg484 commented
> I don't think we should be using `DefaultApplicationContext` class directly which is an internal class.

Agreed, good point. Done in [5ebb76d](https://github.com/micronaut-projects/micronaut-graphql/pull/512/commits/5ebb76d26677c37ee423c2b73b199a71e75846a8)

2024-03-07 14:48 UTC, sdelamo approved these changes

2024-03-07 14:50 UTC, timyates approved these changes

2024-03-07 14:51 UTC, merged